export enum PAGES {
  HOME = "Aluplast | Expertos en aluminio y PVC",
  ABOUT_US = "Sobre nosotros",
  CONTACT = "Contacto",
  CATALOG = 'Catálogo',
  PRODUCT = 'Producto detalle',
  TEXTURES = 'Descubre nuestras nexturas',
  LAST_NEWS = 'Últimas noticias',
  NEWS_DETAIL = 'Noticias detalle',
  SOME_PROJECTS = 'Proyectos destacados',
  PROJECT_DETAIL = 'Proyecto detalle',
  SERVICES = 'Nuestros servicios'
}

export enum PAGES_PATH {
  HOME_PATH = '/',
  ABOUT_US_PATH = 'sobre-aluplast-aberturas-y-cerramientos-de-aluminio-y-pvc',
  CONTACT_PATH = 'contacto-aluplast-entre-rios-argentina',
  CATALOG_PATH = 'productos-de-aluminio-y-pvc',
  PRODUCT_PATH = 'producto-detalle',
  NEWS_PATH = 'ultimas-noticias-aluplast',
  SOME_PROJECTS = 'nuestro-trabajo',
  PROJECT_DETAIL = 'proyecto-detalle',
  NEWS_DETAIL = 'noticia-detalle',
  TEXTURES = 'texturas-tipos-y-tratamientos',
  SERVICES = 'servicios-aluplast-aluminio-pvc'
}

export const keywords = [
  'Aberturas en Urdinarrain',
  'Fabrica de Aberturas en Entre Ríos',
  'Aberturas de Aluminio y PVC en Argentina',
  'Tipologías de Aberturas',
  'Oscilobatientes Urdinarrain',
  'Corredizas de Calidad Argentina',
  'Pivotantes Aluminio Entre Ríos',
  'Soluciones en Aberturas Argentina',
  'Excelencia en Aberturas',
  'Satisfacción del Cliente Aberturas',
  'Ventanas de PVC en Urdinarrain',
  'Puertas de Aluminio Argentina',
  'Ventanas de Diseño en Entre Ríos',
  'Fabricante de Aberturas de Calidad',
  'Ventanas Modernas Urdinarrain',
  'Soluciones Innovadoras en Aberturas',
  'Aberturas a Medida Entre Ríos',
  'Cerramientos de Aluminio Urdinarrain',
  'Calidad Certificada en Aberturas',
  'Diseños Exclusivos de Ventanas',
  'Fachadas de Aluminio en Argentina',
  'Aberturas Eficientes Energéticamente',
  'Puertas de Seguridad Urdinarrain',
  'Ventanas Resistentes al Clima',
  'Fabricante de Puertas Pivotantes',
  'Aberturas para Proyectos Residenciales',
  'Ventanas de Alta Gama Argentina',
  'Aberturas Personalizadas Urdinarrain',
  'Puertas de Entrada de Lujo',
  'Ventanas Antirruido en Entre Ríos'
]
